version: '3'

services:
  mysql_host:
      image: 'bitnami/mysql:5.7.22'
      labels:
        kompose.service.type: nodeport
      ports:
        - '3306:3306'
      volumes:
        - ./volume/mysql:/bitnami
      environment:
        - MYSQL_ROOT_USER=root
        - MYSQL_ROOT_PASSWORD=testpass122
        - MYSQL_DATABASE=sene
        - MYSQL_USER=seneuser
        - MYSQL_PASSWORD=password123